{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "pelicondr-role") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pelicondr-role
rules:
- apiGroups: ["*"]
  resources:
  - "*"
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
{{- end }}
