{{- $serviceAccountName := "pelicondr-admin"}}
{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace $serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName}}
  namespace: {{ .Release.Namespace }}
{{- end }}
