---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqld-config
data:
   mysqld.cnf: |-
     [mysqld]
     pid-file        = /var/run/mysqld/mysqld.pid
     socket          = /var/run/mysqld/mysqld.sock
     datadir         = /var/lib/mysql
     log-bin         = /var/lib/mysql_binlogs/mysql_bin
     server-id       = 1
     #log-error      = /var/log/mysql/error.log
     # By default we only accept connections from localhost
     #bind-address   = 127.0.0.1
     # Disabling symbolic-links is recommended to prevent assorted security risks
     symbolic-links=0

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    pelicon.io/app: dr-mysql-sts
    pelicon.io/component: dr-mysql-sts
  name: dr-mysql-sts
  namespace: default
spec:
  serviceName: dr-mysql-sts-svc
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dr-mysql-sts
  template:
    metadata:
      labels:
        app: dr-mysql-sts
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - image: mysql:5
        args:
        - --ignore-db-dir=lost+found
        imagePullPolicy: Always
        name: dr-mysql-sts
        resources:
          limits:
            cpu: "1"
            memory: "1073741824"
          requests:
            cpu: "1"
            memory: "1073741824"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'dangerous'
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mydata
          subPath: mysqld.cnf
        - mountPath: /var/lib/mysql_binlogs
          name: mybinlogs
      dnsConfig:
        options:
        - name: single-request-reopen
          value: ""
        - name: ndots
          value: "2"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dr-mysql-sts-100.199.142.173
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: mysqld.cnf
            path: mysqld.cnf
          name: mysqld-config
        name: configmap-80646a1f
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        pelicon.io/app: dr-mysql-sts
        pelicon.io/component: dr-mysql-sts
      name: mydata
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "1073741824"
      storageClassName: hw-dr-pool
      volumeMode: Filesystem
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        pelicon.io/app: dr-mysql-sts
        pelicon.io/component: dr-mysql-sts
      name: mybinlogs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "1073741824"
      storageClassName: hw-dr-pool
      volumeMode: Filesystem
