---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqld-config
data:
   mysqld.cnf: |-
     [mysqld]
     pid-file        = /var/run/mysqld/mysqld.pid
     socket          = /var/run/mysqld/mysqld.sock
     datadir         = /var/lib/mysql
     log-bin         = /var/lib/mysql_binlogs/mysql_bin
     server-id       = 1
     #log-error      = /var/log/mysql/error.log
     # By default we only accept connections from localhost
     #bind-address   = 127.0.0.1
     # Disabling symbolic-links is recommended to prevent assorted security risks
     symbolic-links=0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1073741824"
  storageClassName: hw-dr-pool
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mybinlogs
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1073741824"
  storageClassName: hw-dr-pool
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dr-mysql-deploy
  labels:
    app: dr-mysql-deploy
    pelicon.io/app: dr-mysql-deploy
spec:
  selector:
    matchLabels:
      app: dr-mysql-deploy
  template:
    metadata:
      name: dr-mysql-deploy
      labels:
        app: dr-mysql-deploy
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: dr-mysql-deploy
          args:
            - --ignore-db-dir=lost+found
          image: mysql:5
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'dangerous'
          volumeMounts:
            - name: mysqld-config
              mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
              subPath: mysqld.cnf
            - mountPath: /var/lib/mysql
              name: data
            - mountPath: /var/lib/mysql_binlogs
              name: binlogs
          resources:
            limits:
              cpu: "1"
              memory: "4294967296"
      volumes:
        - name: mysqld-config
          configMap:
            name: mysqld-config
        - name: data
          persistentVolumeClaim:
            claimName: mydata
        - name: binlogs
          persistentVolumeClaim:
            claimName: mybinlogs
